### ISSUE TITLE
Add additional Dutch word lists

### ISSUE THREAD

**Issue by metbril** [atoponce/webpassgen#7]
I have read your blog post with great interest and have tried the tool. 

You might be interested in this blog post

https://el-tramo.be/blog/diceware-nl/

that is describing additional (better?) lists for the Dutch language.

I suspect you will at least take a look and hopefully include this in your valuable tool.

**Comment by atoponce** [comment]
All of the word lists for the Diceware generator must come from the official [Diceware site](http://world.std.com/~reinhold/diceware.html). However, if Arnold adds that Dutch word list to his site, I don't have any problems either replacing the current Dutch Diceware word list or adding an alternate.

Another place to put it would be the Alternate generator, and I'm not against adding additional word lists in the Alternate generator, but I want to only have unique word lists that you wouldn't find in the others, like the "Colors" and "Trump" word lists. Because there is already a Dutch word list in Diceware, it doesn't really fit there either.

In my opinion, the best fit is to get the word list approved as the [BIPS-0039 word list](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md). If the Dutch word list you linked to gets approved there, and they have stringent requirements for approval, I will definitely add it to the Bitcoin generator.

Thanks for the link!

**Comment by metbril** [comment]
I understanding your reasoning.
If I find the time I will fork your repo and try to add the lists there for my own purposes. 😄

**Comment by atoponce** [comment]
It just landed as an alternate list on the official Diceware page. I'm now debating if I want to add it or not.

**Comment by atoponce** [comment]
Added as "Dutch (Alt)". The "Diceware Composite Words" word list was chosen from the 4 listed
